version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 8004:5000
  volumes:
  - ./:/app

 mysqldb2:
  image: mysql
  ports:
  - 3304:3304
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
