apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: web
        image: sudipz10028/python-docker-sudip-cnt-crash
        # imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30101